name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.207
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.101
    - name: Restore local copy of ILInt nuget
      run: dotnet restore -s  `pwd` -s https://api.nuget.org/v3/index.json --ignore-failed-sources
    - name: Build with dotnet
      run: dotnet build --configuration Release --no-restore
    - name: Test with dotnet
      run: dotnet test --configuration Release --no-build
