name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core 2.2
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.207
    - name: Install additional dotnet 3.0
      run: sudo apt-get install dotnet-sdk-3.0
    - name: Build and test with dotnet
      run: dotnet test --configuration Release -v:m
